services:
  postgres:
    image: postgres:14.5-alpine
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./docker/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  real-estate-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-volume: